config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :companies do
    resources :books do
      resources :finance_records do
        member do
          put "add_contact"
          delete "remove_contact" 
        end
        resources :notes
        resources :docs do
          member do
            get 'download'
          end
        end
      end
    end

    resources :collabs
    resources :contacts do
      collection do
        get "search"
      end
    end

    member do
      get "friends"
      post "add_friend"
      delete "remove_friend"
    end
  end

  root 'companies#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :finance_record
  include FinanceRecordComponents
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_company
  before_action :check_user_is_collaborator
  before_action :set_book
  before_action :set_record
  before_action :set_note, only: [:edit, :update, :destroy]

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @note.finance_record = @record

    respond_to do |format|
      if @note.save
        format.html { redirect_to :back, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: "Note was deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = @record.notes.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:content, :record_id)
    end

    include SetBookAndRecord

    include UserPermissionCheck
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.haml
= form_for [@company, @book, @record, @note] do |f|
  - if @note.errors.any?
    #error_explanation
      %h2= "#{pluralize(@note.errors.count, "error")} prohibited this note from being saved:"
      %ul
        - @note.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.text_area :content, placeholder: "Type note here."
  .actions
    = f.submit 'Save'

app/views/notes/_note.haml
%p
  = note.content
  %br
  = link_to "Delete", company_book_finance_record_note_path(note.company,
    note.book, note.finance_record, note), method: "Delete",
    connfirm: "Are you sure yu want to delete?", class: "btn btn-xs btn-danger"
%hr

app/views/notes/edit.html.haml
%h1 Editing note

= render 'form'

= link_to 'Show', @note
\|
= link_to 'Back', notes_path

app/views/notes/index.html.haml
%h1 Listing notes

%table
  %tr
    %th Content
    %th Record
    %th
    %th
    %th

  - @notes.each do |note|
    %tr
      %td= note.content
      %td= note.record
      %td= link_to 'Show', note
      %td= link_to 'Edit', edit_note_path(note)
      %td= link_to 'Destroy', note, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Note', new_note_path

app/views/notes/new.html.haml
%h1 New note

= render 'form'

= link_to 'Back', notes_path

app/views/notes/show.html.haml
%p#notice= notice

%p
  %b Content:
  = @note.content
%p
  %b Record:
  = @note.record

= link_to 'Edit', edit_note_path(@note)
\|
= link_to 'Back', notes_path