config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :companies do
    resources :books do
      resources :finance_records do
        member do
          put "add_contact"
          delete "remove_contact" 
        end
        resources :notes
        resources :docs do
          member do
            get 'download'
          end
        end
      end
    end

    resources :collabs
    resources :contacts do
      collection do
        get "search"
      end
    end

    member do
      get "friends"
      post "add_friend"
      delete "remove_friend"
    end
  end

  root 'companies#index'

end

app/models/collab.rb
class Collab < ActiveRecord::Base
  belongs_to :company
end

app/controllers/collabs_controller.rb
class CollabsController < ApplicationController
  before_action :set_company
  before_action :set_collab, only: [:show, :edit, :update, :destroy]
  
  # GET /collabs
  # GET /collabs.json
  def index
    @collabs = Collab.all
  end

  # GET /collabs/1
  # GET /collabs/1.json
  def show
  end

  # GET /collabs/new
  def new
    @collab = Collab.new
  end

  # GET /collabs/1/edit
  def edit
  end

  # POST /collabs
  # POST /collabs.json
  def create
    @collab = Collab.new(collab_params)
    @collab.company = @company
    respond_to do |format|
      if @collab.save
        format.html { redirect_to company_collabs_path(@company), notice: 'Collab was successfully created.' }
        format.json { render :show, status: :created, location: @collab }
      else
        format.html { render :new }
        format.json { render json: @collab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collabs/1
  # PATCH/PUT /collabs/1.json
  def update
    respond_to do |format|
      if @collab.update(collab_params)
        format.html { redirect_to company_collabs_path(@company), notice: 'Collab was successfully updated.' }
        format.json { render :show, status: :ok, location: @collab }
      else
        format.html { render :edit }
        format.json { render json: @collab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collabs/1
  # DELETE /collabs/1.json
  def destroy
    @collab.destroy
    respond_to do |format|
      format.html { redirect_to collabs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collab
      @collab = Collab.find(params[:id])
    end
    
    def set_company
      @company = current_user.companies.find params[:company_id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collab_params
      params.require(:collab).permit(:email, :company_id)
    end
end

app/helpers/collabs_helper.rb
module CollabsHelper
end

app/views/collabs/_form.html.haml
= form_for([@company, @collab]) do |f|
  - if @collab.errors.any?
    #error_explanation
      %h2= "#{pluralize(@collab.errors.count, "error")} prohibited this collab from being saved:"
      %ul
        - @collab.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit 'Save'

app/views/collabs/edit.html.haml
%h1 Editing collab

= render 'form'

= link_to 'Show', company_collab_path(@collab.company, @collab)
\|
= link_to 'Back', company_collabs_path(@collab.company)

app/views/collabs/index.html.haml
%h1 Listing collabs

%table
  %tr
    %th Email
    %th Company
    %th
    %th
    %th

  - @collabs.each do |collab|
    %tr
      %td= collab.email
      %td= collab.company
      %td= link_to 'Show', company_collab_path(collab.company, collab)
      %td= link_to 'Edit', edit_company_collab_path(collab.company, collab)
      %td= link_to 'Destroy', company_collab_path(collab.company, collab),
      :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Collab', new_company_collab_path

app/views/collabs/new.html.haml
%h1 New collab

= render 'form'

= link_to 'Back', company_collabs_path(@company)

app/views/collabs/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @collab.email
%p
  %b Company:
  = @collab.company

= link_to 'Edit', edit_collab_path(@collab)
\|
= link_to 'Back', collabs_path