config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :companies do
    resources :books do
      resources :finance_records do
        member do
          put "add_contact"
          delete "remove_contact" 
        end
        resources :notes
        resources :docs do
          member do
            get 'download'
          end
        end
      end
    end

    resources :collabs
    resources :contacts do
      collection do
        get "search"
      end
    end

    member do
      get "friends"
      post "add_friend"
      delete "remove_friend"
    end
  end

  root 'companies#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  validates :name, presence: true
  has_many :books
  has_many :finance_records, through: :books
  has_many :contacts
  belongs_to :user
  has_and_belongs_to_many :collaborators, class_name: "User"

  SearchableColumns = [:name, :description]
  include Searchable

  # Returns true if the user can collaborate for the company
  def collaborator? user_obj
    (self.user == user_obj) or (self.collaborators.index(user_obj))
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_company, only: [:show, :edit, :update, :destroy, :friends,
    :add_friend, :remove_friend]

  # GET /companies
  # GET /companies.json
  def index
    @companies = current_user.companies.order(:name).page(params[:page]).per(10)
    @companies = @companies.search(params[:s]) unless params[:s].empty? if params[:s]
    @collab_companies = current_user.collab_companies.order(:name).page(params[:page]).per(10)
    @collab_companies = @collab_companies.search(params[:s]) unless params[:s].empty? if params[:s]
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    @company.user = current_user
    
    respond_to do |format|
      if @company.save
        format.html { redirect_to companies_url, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  def friends
  end

  def add_friend
    user = User.where(email: params[:email]).first
    if user
      @company.collaborators << user
      redirect_to :back, notice: "#{user.email} added"
    else
      redirect_to :back, notice: "#{params[:email]} not registered. Plese tell them to register and add them."
    end
  end

  def remove_friend
    user = User.find(params[:collab_id])
    @company.collaborators.delete user
    redirect_to :back, notice: "#{user.email} removed from friends list"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :description)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.haml
.col-md-6
  .panel.panel-primary
    .panel-heading
      .panel-title= link_to company.name, company_books_path(company)
    .panel-body
      = link_to pluralize(company.books.count, "Book"), company_books_path(company), class: "btn btn-default"
      = link_to pluralize(company.contacts.count, "Contact"), company_contacts_path(company), class: "btn btn-default"
      = link_to pluralize(company.collaborators.count, "Friend"), friends_company_path(company), class: "btn btn-default"
      = link_to "Edit", edit_company_path(company), class: "btn btn-default"
      = link_to "Delete", company, method: :delete, class: "btn btn-default", "data-confirm" => "Really want to delete this company?"
    .panel-footer= company.description

app/views/companies/_form.html.haml
= form_for(@company, html:{class: "form-horizontal"}) do |f|
  - if @company.errors.any?
    #error_explanation
      %h2= "#{pluralize(@company.errors.count, "error")} prohibited this company from being saved:"
      %ul
        - @company.errors.full_messages.each do |msg|
          %li= msg

  .field.form-group
    = f.label :name, class: "col-sm-2 control-label"
    .col-sm-6
      = f.text_field :name, class: "form-control"
  .field.form-group
    = f.label :description, class: "col-sm-2 control-label"
    .col-sm-6
      = f.text_area :description, class: "form-control"
 
  .actions.col-sm-offset-2.col-sm-6
    = f.submit 'Save', class: "btn btn-default"

app/views/companies/_top_bar.html.haml
.panel
  .panel-body
    = link_to raw('<span class="glyphicon glyphicon-home"></span>'), root_path,
      class: "btn btn-default"
    = link_to 'New Company', new_company_path, class: "btn btn-default"
    .btn-group
      %button.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
        %span.glyphicon.glyphicon-cog
        %span.caret
      %ul.dropdown-menu{:role => "menu"}
        %li
          = link_to raw('<span class="glyphicon glyphicon-user"></span> Signout'), destroy_user_session_path,
            method: :delete
    .pull-right
      = render partial: "common/search_form"

app/views/companies/edit.html.haml
= render partial: 'top_bar'

%h1 Editing company

= render 'form'

app/views/companies/friends.haml
= render partial: 'books/top_bar'

.row
  .col-md-12
    %h1
      = @company.name
      \/
      Friends
    %p
      Friends are trusted people whom you can add to your company so that they can add / modify
      and delete financial records. The user needs to have been registered for him / her to be
      addedas friend.

.row
  .col-md-12
    = form_tag(add_friend_company_path(@company)) do
      = email_field_tag :email, nil,placeholder: "Enter email"
      = submit_tag "Add Person"
  %ul
    - for collab in @company.collaborators do
      %li
        = collab.email
        = link_to "Remove", remove_friend_company_path(@company, collab_id: collab.id), method: :delete

app/views/companies/index.html.haml
= render partial: 'top_bar'

%h1 Your companies

.row= render @companies

.row
  .col-md-12= paginate @companies, :theme => 'twitter-bootstrap-3'

%h1 Friends companies

.row= render @collab_companies

.row
  .col-md-12= paginate @collab_companies, :theme => 'twitter-bootstrap-3'

app/views/companies/new.html.haml
= render partial: 'top_bar'

%h1 Creat a company

= render 'form'

app/views/companies/show.html.haml
.panel.panel-primary
  .panel-heading= @company.name
  .panel-body
    = link_to "14 Books", "#", class: "btn btn-default"
    = link_to "7245 Contacts", "#", class: "btn btn-default"
    = link_to "Edit", edit_company_path(@company), class: "btn btn-default"
    = link_to "Delete", @company, class: "btn btn-default", method: :delete,
      "data-confirm" => "Do you really want to delete?"

= link_to "Add New Book", new_company_book_path(@company),
  class: "btn btn-default"

%table.table.table-stripped
  %tr
    %th Book name
    %th Income
    %th Expense
    %th Pen - Income
    %th Pen - Expense
    %th Balance
  = render @company.books